// <auto-generated />
using CrudOperationOfOneTableAndAuthenticationAuthorization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudOperationOfOneTableAndAuthenticationAuthorization.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240213052937_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudOperationOfOneTableAndAuthenticationAuthorization.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ali pur Chatha District Gujjranwala",
                            Email = "saad2@gmail.com",
                            FName = "Akbar Ali",
                            Name = "Saad",
                            PhoneNumber = "03026199105",
                            RollNo = "BCS19-223"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gujjranwala",
                            Email = "usman123@gmail.com",
                            FName = "Javaid",
                            Name = "Usman",
                            PhoneNumber = "030432723282",
                            RollNo = "BCS19-03"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Peoples Colony Gujjranwala",
                            Email = "umairaslam008@gmail.com",
                            FName = "Aslam",
                            Name = "Umair",
                            PhoneNumber = "030432287282",
                            RollNo = "BCS19-34"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
